[package]
name = "silly-comments"
version = "0.1.0"
authors = ["Ed Cragg <drq.11235@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron = "0.6.1"
diesel = "1.4.3"
pulldown-cmark = "0.6.1"
